### ISSUE TITLE
Not compatible with angular universal 6

### ISSUE THREAD

**Issue by kvincent3** [uiuniversal/ngu-carousel#44]
I have the following error for angular universal 6 : 

(function (exports, require, module, __filename, __dirname) { import { Component, HostBinding } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by corentin-gautier** [comment]
if you're not using webpack to compile you're project: use it. This is a very common error, happens with a lot of libraries. (https://github.com/angular/angular-cli/wiki/stories-universal-rendering#step-5-setup-a-webpack-config-to-handle-this-node-serverts-file-and-serve-your-application)
